# File: .readthedocs.yaml

version: 2

sphinx:
  configuration: docs/conf.py

build:
  image: latest
  apt_packages:
    - gfortran

python:
  version: 3.8.10
  install:
    - requirements: requirements1.txt
    - requirements: requirements2.txt
    - requirements: requirements3.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: .