# File: .readthedocs.yaml

version: 2

sphinx:
  configuration: docs/conf.py

build:
  image: latest
  apt_packages:
    - gfortran

python:
  version: 3.7
  install:
    - requirements: requirements1.txt
    - requirements: requirements2.txt